export const SPORT_PRESETS = {
  cricket: {
    label: 'Cricket',
    icon: '🏏',
    description: 'IPL-style auction with overseas cap and tiered bid increments',
    playerRoles: ['Batsman', 'Bowler', 'All-Rounder', 'Wicket-Keeper'],
    currency: 'INR',
    currencySymbol: '₹',
    currencyUnit: 'lakh',
    defaultPursePerTeam: 12500,
    minSquadSize: 18,
    maxSquadSize: 25,
    maxOverseasPlayers: 8,
    minMalePlayers: 0,
    minFemalePlayers: 0,
    bidIncrementTiers: [
      { upToAmount: 100, increment: 5 },
      { upToAmount: 500, increment: 20 },
      { upToAmount: 1000, increment: 50 },
      { upToAmount: 999999999, increment: 100 },
    ],
    rtmEnabled: false,
    rtmCardsPerTeam: 1,
  },
  badminton: {
    label: 'Badminton',
    icon: '🏸',
    description: 'Gender-balanced squads with category-based player tiers',
    playerRoles: ['A+', 'A', 'B', 'F+', 'F'],
    currency: 'CR',
    currencySymbol: '₹',
    currencyUnit: 'CR',
    defaultPursePerTeam: 100,
    minSquadSize: 8,
    maxSquadSize: 15,
    maxOverseasPlayers: 0,
    minMalePlayers: 6,
    minFemalePlayers: 2,
    bidIncrementTiers: [
      { upToAmount: 10, increment: 0.5 },
      { upToAmount: 20, increment: 1 },
      { upToAmount: 999999999, increment: 2 },
    ],
    rtmEnabled: false,
    rtmCardsPerTeam: 1,
  },
};

export const SPORT_KEYS = Object.keys(SPORT_PRESETS);
